[workspace]
resolver = "3"
members = ["griffin-web", "griffin-domain", "griffin-macros", "cargo-griffin", "examples/*"]

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.97"
license = "MIT OR Apache-2.0"
repository = "https://github.com/griffin-rs/griffin"
readme = "README.md"
keywords = ["web", "framework", "liveview", "axum"]
categories = ["web-programming"]
